services:
  - type: web
    plan: free
    name: MachiBae
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m ShizukaXMusic
    repo: https://github.com/Cutey02/As.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: MUSIC_BOT_NAME
        sync: false
      - key: MONGO_DB_URI
        sync: false 
      - key: OWNER_ID
        sync: false
      - key: STRING_SESSION
        sync: false    
    autoDeploy: false
